# Generated by Django 3.0 on 2023-08-01 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def copy_data_from_old_letting_to_letting(apps, schema_editor):
    # Obtenez les modèles des anciennes et nouvelles tables
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    Letting = apps.get_model('lettings', 'Letting')

    # Copiez les données de l'ancienne table Letting vers la nouvelle table Letting
    old_data = OldLetting.objects.all()
    for old_entry in old_data:
        Letting.objects.create(
            title=old_entry.title,
            address=old_entry.address,
        )


def copy_data_from_old_address_to_address(apps, schema_editor):
    # Obtenez les modèles des anciennes et nouvelles tables
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    Address = apps.get_model('lettings', 'Address')

    # Copiez les données de l'ancienne table Address vers la nouvelle table Address
    old_data = OldAddress.objects.all()
    for old_entry in old_data:
        Address.objects.create(
            number=old_entry.number,
            street=old_entry.street,
            city=old_entry.city,
            state=old_entry.state,
            zip_code=old_entry.zip_code,
            country_iso_code=old_entry.country_iso_code,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('country_iso_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Letting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lettings.Address')),
            ],
        ),
        migrations.RunPython(copy_data_from_old_letting_to_letting),
        migrations.RunPython(copy_data_from_old_address_to_address),
    ]
