# Generated by Django 3.0 on 2023-08-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name_plural': 'lettings'},
        ),
    ]
